openapi: 3.0.0
info:
  version: '1'
  title: BootstrAPI for Crowd
  description: This plugin provides methods for accessing configuration for Crowd.
  contact:
    url: https://github.com/deftdevs/bootstrapi
    email: opensource@deftdevs.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
security:
  - basicAuth: []
servers:
  - url: "{url}/rest/bootstrapi/1/"
    variables:
      url:
        default: http://localhost:4990/crowd
        description: URL with protocol, domain, port and path
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths: {}
