name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  merge_group:

jobs:
  compile:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run compile
      run: mvn -B compile

  unit-tests:
    needs: compile

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run unit tests and Sonarcloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B test sonar:sonar

  integration-tests:
    needs: unit-tests

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        product:
          - confluence
          - crowd
          - jira

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run integration tests
      run: mvn -B -pl ${{ matrix.product }} -am verify
