name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  merge_group:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run build
      run: mvn -B package -DskipTests

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          **/target/*.jar
          **/target/*.obr

  unit-tests:
    needs: build

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run unit tests and Sonarcloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B test sonar:sonar

  integration-tests:
    needs: unit-tests

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        product:
          - confluence
          - crowd
          - jira

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run integration tests
      run: mvn -B -pl ${{ matrix.product }} -am verify

  apcc:
    needs: build

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        product:
          - crowd
          - jira
          # APCC currently does not support confluence...

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Run APCC
        run: |
          mvn -B install -DskipTests
          cd ${{ matrix.product }}
          mvn -B dependency:get -DgroupId=de.aservo -DartifactId=atlassian-plugin-compatibility-check -Dversion=0.0.4
          mvn -B dependency:copy -Dartifact=de.aservo:atlassian-plugin-compatibility-check:0.0.4 -DoutputDirectory=.
          java -jar atlassian-plugin-compatibility-check-0.0.4.jar "${{ matrix.product }}.version"
