name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  merge_group:

jobs:
  package:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Build Maven packages
      run: mvn -B package -DskipTests

  unit-tests:
    needs: package

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Run unit tests
      run: mvn -B test

  integration-tests:
    needs: unit-tests

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        product:
          - confluence
          - crowd
          - jira

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Install Maven packages
      run: mvn -B install -DskipTests

    - name: Run integration tests
      run: mvn -B -pl ${{ matrix.product }} ${{ matrix.product }}:integration-test
